### ISSUE TITLE
Upar tema no GitHub

### ISSUE THREAD

**Issue by andrenakazato** [wpbrasil/wpbr-oportunidades#5]
Para que eu começe o workflow de atualização do tema, preciso que ele esteja aqui no GitHub pois creio eu que tenha algumas modificações em cima do tema base do WordPress. Caso alguém tenha uma outra sugestão, só comentar aqui.

**Comment by vmassuchetto** [comment]
Oi André.

O Tema é este daqui mesmo. =)

Ele é filho do twentythirteen:
https://github.com/wpbrasil/wpbr-oportunidades/blob/master/style.css#L7
